// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znuwvmrftqoorgapbmgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpudXd2bXJmdHFvb3JnYXBibWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTM0ODUsImV4cCI6MjA1OTU2OTQ4NX0.uXxfCPVHEi2pEI7ywRErripIjfXegnOowGJzFWzPch8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);